var userClickedPattern = []; // empty array
var buttonColours = ["red", "blue", "green", "yellow"];  // array with items as button id names
var gamePattern = []; //empty array

var started = false;  // variable to keep track whether the game has started to keep changing the h1 at each level.
var level = 0; // Create a new variable called level and start at level 0.

$(document).keypress(function()  // takes key press and if it is the first one then nextSequence() is called.
{
    if(!started)
    {
        $("h1").text("Level "+level);
        nextSequence();
        started = true;
    }
})

$(".btn").on("click",function()  // Using JQuery to detect when any of the buttons are clicked and trigger a handler function.
{
    var userChosenColour = $(this).attr("id"); //new variable called userChosenColour to store the id of the button that got clicked.
    userClickedPattern.push(userChosenColour);  // Adding this button id to the array userClickedPattern

    playSound(userChosenColour); // the id of the color box on which user clicked is passed as an argument

    animatePress(userChosenColour); // This called function changes its style.

    checkAnswer(userClickedPattern.length-1);  // we check whether user sequence is matching with gamepattern generated by nextSequence()
});


function checkAnswer(currentLevel) // we check whether user sequence is matching with gamepattern generated by nextSequence()
{
    if(gamePattern[currentLevel] == userClickedPattern[currentLevel])  // if elements are matching
    {
        console.log("Success"); 
        if(gamePattern.length == userClickedPattern.length)  // if user has completed the whole sequence
        {
            setTimeout(function()
            {
                nextSequence();  // again calling nextSequence() to add to the sequence.
            },1000);  // time delay 1000 millisecond
        }
    }
    else
    {
        console.log("wrong"); 
        
        playSound("wrong");

        $("body").addClass("game-over");  // class added

        setTimeout(function()  // class removed
        {
            $("body").removeClass("game-over");
        },200);

        $("#level-title").text("Game Over, Press Any Key to Restart");  // h1 changed

        startOver();  // calling startOver function defined at the bottom
    }
}



function nextSequence()
{
    userClickedPattern = [];  // once new sequence starts userpattern is emptied
    level++;  // increasing level to 1.
    $("h1").text("Level "+level);  // displaying h1 as level 1.
    
    var randomNumber = Math.floor(Math.random()*4); // generating random numbers
    var randomChosenColour = buttonColours[randomNumber]; //selecting colors randomly
    gamePattern.push(randomChosenColour); //pushing random color to gamePattern array

    $("#"+randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);  // fading in and out the random button
    var audio = new Audio("sounds/"+randomChosenColour+".mp3");  // playing sound for random button when website is opened
    audio.play();
}

function playSound(name)  // it plays the sound of the button pressed
{
    var audio = new Audio("sounds/"+name+".mp3");   // audio fetched from audio folder
    audio.play();
}

function animatePress(currentColour)  // this function is used to change style of the clicked button from 100 miliseconds
{
    $("#"+currentColour).addClass("pressed");  // adding the class to change style

    setTimeout(function()  // removing style after 100 mmiliseconds.
    {
        $("#"+currentColour).removeClass("pressed");
    },100);
}

function startOver() // resetting bellow values
{
    level = 0;
    gamePattern = [];
    started = false;
}